development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['JOB_NAME'] || 'deployer' %>_development
  pool: 5
  username: <%= ENV['USER'] %>
  password: <%= ENV['USER'] == "jenkins" ? 'jenkins' : nil %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['JOB_NAME'] || 'deployer' %>_test
  pool: 5
  username: <%= ENV['USER'] %>
  password: <%= ENV['USER'] == "jenkins" ? 'jenkins' : nil %>

